services:
  # ─── HDFS ────────────────────────────────────────────────────
  namenode:
    image: apache/hadoop:3.3.5
    platform: linux/amd64
    container_name: namenode
    hostname: namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    env_file:
      - ./hadoop_config/.env
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/nameNode
      - ./hadoop_tmp:/opt/hadoop/data/tmp
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./scripts/start-hdfs.sh:/start-hdfs.sh
      - ./data:/data
    ports:
      - "9870:9870"
      - "9000:9000"
    command: ["/bin/bash", "/start-hdfs.sh"]
    networks:
      - zomato_network

  datanode1:
    image: apache/hadoop:3.3.5
    platform: linux/amd64
    container_name: datanode1
    hostname: datanode1
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    env_file:
      - ./hadoop_config/.env
    volumes:
      - ./hadoop_datanode1:/opt/hadoop/data/dataNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./scripts/init-datanode.sh:/init-datanode.sh
    ports:
      - "9864:9864"
    depends_on:
      - namenode
    command: ["/bin/bash", "/init-datanode.sh"]
    networks:
      - zomato_network

  # ─── KAFKA ───────────────────────────────────────────────────
  kafka:
    image: quay.io/strimzi/kafka:0.51.0-kafka-4.2.0
    container_name: kafka
    hostname: kafka
    command:
      - sh
      - -c
      - |
        cp ./config/server.properties /tmp/server.properties
        cat /opt/kafka/custom/server-overrides.properties >> /tmp/server.properties
        ./bin/kafka-storage.sh format \
          --ignore-formatted \
          --standalone \
          -t $$KAFKA_CLUSTER_ID \
          -c /tmp/server.properties
        ./bin/kafka-server-start.sh /tmp/server.properties
    env_file:
      - ./kafka_config/kafka.env
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - ./kafka_config/server-overrides.properties:/opt/kafka/custom/server-overrides.properties
    networks:
      - zomato_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - zomato_network

  # ─── SPARK ───────────────────────────────────────────────────
  spark-master:
    image: apache/spark:4.0.0
    container_name: spark-master
    depends_on:
      - kafka
      - namenode
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - HOME=/tmp
      - SPARK_SUBMIT_OPTS=-Duser.home=/tmp
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=zomato-orders
      - DASHBOARD_DIR=/opt/zomato/dashboard_data
      - CHECKPOINT_DIR=/opt/zomato/checkpoints
    ports:
      - "7077:7077"
      - "8082:8080"
    volumes:
      - ./jobs:/opt/zomato/jobs
      - ./checkpoints:/opt/zomato/checkpoints
      - ./dashboard_data:/opt/zomato/dashboard_data
      - ./data:/opt/zomato/data
      - ./hadoop_config:/opt/hadoop/etc/hadoop
    networks:
      - zomato_network

  spark-worker:
    image: apache/spark:4.0.0
    container_name: spark-worker
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8083:8081"
    volumes:
      - ./jobs:/opt/zomato/jobs
      - ./checkpoints:/opt/zomato/checkpoints
      - ./dashboard_data:/opt/zomato/dashboard_data
      - ./data:/opt/zomato/data
      - ./hadoop_config:/opt/hadoop/etc/hadoop
    networks:
      - zomato_network

  # ─── STREAMLIT DASHBOARD ─────────────────────────────────────
  streamlit:
    build: ./dashboard
    container_name: streamlit
    depends_on:
      - spark-master
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard_data:/app/dashboard_data
    environment:
      - DASHBOARD_DIR=/app/dashboard_data
    networks:
      - zomato_network

networks:
  zomato_network:
    name: big-data-project-class-b_team3
    driver: bridge
